#!/bin/bash

send_force() {
    if [[ $# -eq 0 ]]; then
        message="No Message"
    else
        message="$*"
    fi

    date=$(date +'%Y-%m-%d')

    echo "Adding files..."
    sleep 1
    git add .
    clear

    echo "Committing changes..."
    sleep 1
    git commit -m "$date: $message"


    echo "Pushing changes..."
    sleep 1
    git push --force

    echo "Everything is now up-to-date! :D"
}

send_force "$@"
